FROM quay.io/soketi/soketi:latest-16-debian AS soketi

ARG DEFAULT_APP_ID
ENV DEFAULT_APP_ID=$DEFAULT_APP_ID

ARG DEFAULT_APP_KEY
ENV DEFAULT_APP_KEY=$DEFAULT_APP_KEY

ARG DEFAULT_APP_SECRET
ENV DEFAULT_APP_SECRET=$DEFAULT_APP_SECRET

ARG DEFAULT_APP_SECRET
ENV DEFAULT_APP_SECRET=$DEFAULT_APP_SECRET
